### ISSUE TITLE
[REJECTED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [paxos1977/OneTimePad#1]
Dear Mr. Gilbert,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by ohz10** [comment]
1. [Have Space Suit - Will Travel](https://www.visualstudio.com/vs/community/)
2. arc4random doesn't exist on Windows, and I've no interest in doing a port
3. I'd recommend you investigate [WSL](https://blogs.msdn.microsoft.com/wsl/2016/04/22/windows-subsystem-for-linux-overview/)
